/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import ManageAirliners.*;
import ManageCustomers.*;
import ManageFlightSchedules.*;
import Business.*;
import java.awt.CardLayout;
/**
 *
 * @author BHAGAT
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    private TravelAgency travelAgency;
    public TravelAgencyMain() {
        initComponents();
        travelAgency = new TravelAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        mngAirlinerButton = new javax.swing.JButton();
        mngFlightSchButton = new javax.swing.JButton();
        mngCustButton = new javax.swing.JButton();
        cardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(0, 204, 204));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        controlJPanel.setBackground(new java.awt.Color(211, 245, 245));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mngAirlinerButton.setText("Manage Airliners");
        mngAirlinerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngAirlinerButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(mngAirlinerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 60));

        mngFlightSchButton.setText("Manage Flight Schedules");
        mngFlightSchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngFlightSchButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(mngFlightSchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 60));

        mngCustButton.setText("Manage Customers");
        mngCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCustButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(mngCustButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 60));

        jSplitPane1.setLeftComponent(controlJPanel);

        cardSequenceJPanel.setBackground(new java.awt.Color(211, 245, 245));
        cardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(cardSequenceJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngAirlinerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngAirlinerButtonActionPerformed
        // TODO add your handling code here:
        ManageAirliners manageAirliners = new ManageAirliners(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("TravelAgencyMain",manageAirliners);
        CardLayout cardLayout=(CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
        
    }//GEN-LAST:event_mngAirlinerButtonActionPerformed

    private void mngFlightSchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngFlightSchButtonActionPerformed
        // TODO add your handling code here:
        ManageFlightSchPanel manageFlightSchPanel = new ManageFlightSchPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("ManageFlightSch",manageFlightSchPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_mngFlightSchButtonActionPerformed

    private void mngCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCustButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerPanel manageCustomerPanel = new ManageCustomerPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("ManageCustomer",manageCustomerPanel);
       CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
       cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_mngCustButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardSequenceJPanel;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton mngAirlinerButton;
    private javax.swing.JButton mngCustButton;
    private javax.swing.JButton mngFlightSchButton;
    // End of variables declaration//GEN-END:variables
}
