/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHAGAT
 */
public class AirlinerForFlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerForFlight
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public AirlinerForFlightPanel(TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency= travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }
    public void reload()
    {
        DefaultTableModel dtm = (DefaultTableModel)airlinersTable1.getModel();
        dtm.setRowCount(0);
        for (Map.Entry<String,Airliners> it : travelAgency.getListOfAirliner().entrySet())
        {
            Object row[] = new Object[1];
            row[0] = it.getValue();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlinersTable = new javax.swing.JTable();
        viewDetailsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        selectAirplane = new javax.swing.JLabel();
        airlinerjScrollPane = new javax.swing.JScrollPane();
        airlinersTable1 = new javax.swing.JTable();
        viewAirplanesButton = new javax.swing.JButton();
        AirplanejScrollPane = new javax.swing.JScrollPane();
        airplanesTable = new javax.swing.JTable();
        scheduleFlightButton = new javax.swing.JButton();
        AirlinerTable = new javax.swing.JLabel();
        Airplane = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        airlinersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinersTable);

        viewDetailsButton.setText("View Details");

        setBackground(new java.awt.Color(210, 248, 248));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 84, 170, 48));

        selectAirplane.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        selectAirplane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectAirplane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        selectAirplane.setText("    SELECT AIRLINER & AIRPLANE FOR FLIGHT ");
        add(selectAirplane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 660, -1));

        airlinersTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airlinerjScrollPane.setViewportView(airlinersTable1);

        add(airlinerjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 100, -1, 136));

        viewAirplanesButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        viewAirplanesButton.setText("View Airplanes");
        viewAirplanesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirplanesButtonActionPerformed(evt);
            }
        });
        add(viewAirplanesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 49));

        airplanesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Id", "Model Num", "Company", "Manuf. Year", "Total Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AirplanejScrollPane.setViewportView(airplanesTable);

        add(AirplanejScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 280, -1, 107));

        scheduleFlightButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        scheduleFlightButton.setText("Schedule Flight");
        scheduleFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleFlightButtonActionPerformed(evt);
            }
        });
        add(scheduleFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 49));

        AirlinerTable.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        AirlinerTable.setText("Airliner Table:");
        add(AirlinerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 74, -1, -1));

        Airplane.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        Airplane.setText("Airplane Table:");
        add(Airplane, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 254, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 550, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleFlightButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = airplanesTable.getSelectedRow();
        if (selectedRow < 0 )
            JOptionPane.showMessageDialog(null, "Please select a row from Airplane Table");
        else
        {
            Airplane airplane= (Airplane) airplanesTable.getValueAt(selectedRow, 0);
            FlightPanel flightPanel = new FlightPanel(travelAgency,airplane,cardSequenceJPanel);
            cardSequenceJPanel.add("Flight",flightPanel);
            CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
            cardLayout.next(cardSequenceJPanel);
        }
    }//GEN-LAST:event_scheduleFlightButtonActionPerformed

    private void viewAirplanesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirplanesButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinersTable1.getSelectedRow();
        if (selectedRow < 0 )
            JOptionPane.showMessageDialog(null, "Please select a row from Airliner Table");
        else
        {
            Airliners airliners = (Airliners) airlinersTable1.getValueAt(selectedRow, 0);
            Fleet fleet = airliners.getFleet();
            DefaultTableModel dtm = (DefaultTableModel) airplanesTable.getModel();
            dtm.setRowCount(0);
            for (Airplane airplane: fleet.getListOfAirplanes())
            {
                Object row[] = new Object[5];
                row[0] = airplane;
                row[1] = airplane.getModelNumber();
                row[2]=airplane.getManufacturingCompany();
                row[3]=airplane.getManufacturingYear();
                row[4]=airplane.getTotalSeats();
                dtm.addRow(row);
            }
            //airlinersTable1.setEnabled(false);
        }
    }//GEN-LAST:event_viewAirplanesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirlinerTable;
    private javax.swing.JLabel Airplane;
    private javax.swing.JScrollPane AirplanejScrollPane;
    private javax.swing.JScrollPane airlinerjScrollPane;
    private javax.swing.JTable airlinersTable;
    private javax.swing.JTable airlinersTable1;
    private javax.swing.JTable airplanesTable;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton scheduleFlightButton;
    private javax.swing.JLabel selectAirplane;
    private javax.swing.JButton viewAirplanesButton;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
}
