/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author BHAGAT
 */
public class CreateAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerPanel
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public CreateAirlinerPanel(TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
    }
    public void disableFields()
    {
        nameTextField.setEnabled(false);
        iATATextField.setEnabled(false);
        iCAOTextField.setEnabled(false);
        countryTextField.setEnabled(false);
        mainHubTextField.setEnabled(false);
        addAirplanesButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        Airliner = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        iata = new javax.swing.JLabel();
        iATATextField = new javax.swing.JTextField();
        icao = new javax.swing.JLabel();
        iCAOTextField = new javax.swing.JTextField();
        mainhub = new javax.swing.JLabel();
        mainHubTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        country = new javax.swing.JLabel();
        addAirplanesButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(211, 246, 246));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 160, 50));

        Airliner.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Airliner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        Airliner.setText("CREATE AIRLINER PROFILE");
        add(Airliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 420, -1));

        Name.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        Name.setText("Name");
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 151, -1));

        iata.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        iata.setText("IATA");
        add(iata, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));
        add(iATATextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 150, -1));

        icao.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        icao.setText("ICAO");
        add(icao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        add(iCAOTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 150, -1));

        mainhub.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        mainhub.setText("Main Hub");
        add(mainhub, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        add(mainHubTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 150, -1));
        add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 150, -1));

        country.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        country.setText("Country");
        add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        addAirplanesButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addAirplanesButton.setText("Add Airplanes");
        addAirplanesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirplanesButtonActionPerformed(evt);
            }
        });
        add(addAirplanesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 350, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void addAirplanesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirplanesButtonActionPerformed
        // TODO add your handling code here:
        if ((nameTextField.getText().isEmpty()) || (iATATextField.getText().isEmpty()) || 
            (iCAOTextField.getText().isEmpty()) || (countryTextField.getText().isEmpty()) ||
            (mainHubTextField.getText().isEmpty()))
            JOptionPane.showMessageDialog(null, "Please enter the airliner details before adding airplane", "Error", 0);
        else
        {
            try
            {
                Airliners airliners=travelAgency.addAirliners(nameTextField.getText());
                airliners.setAirlines(nameTextField.getText());
                airliners.setCountry(countryTextField.getText());
                airliners.setMainHub(mainHubTextField.getText());
                airliners.setiATA(iATATextField.getText());
                airliners.setiCAO(iCAOTextField.getText());
                Fleet fleet=new Fleet();
                fleet.setAirliners(airliners);
                airliners.setFleet(fleet);
                FlightSchedule flightSchedule = travelAgency.getMasterSchedule().addFlightSchedule(airliners);
                airliners.setFlightSchedule(flightSchedule);
                //flightSchedule.setAirliners(airliners);
                AddingAirplanePanel addingAirplanePanel = new AddingAirplanePanel(fleet,cardSequenceJPanel);
                cardSequenceJPanel.add("AddingAirplane",addingAirplanePanel);
                CardLayout cardLayout= (CardLayout) cardSequenceJPanel.getLayout();
                cardLayout.next(cardSequenceJPanel);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Existing Airliner", "Error", 0);
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_addAirplanesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Airliner;
    private javax.swing.JLabel Name;
    private javax.swing.JButton addAirplanesButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel country;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField iATATextField;
    private javax.swing.JTextField iCAOTextField;
    private javax.swing.JLabel iata;
    private javax.swing.JLabel icao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mainHubTextField;
    private javax.swing.JLabel mainhub;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
