/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import com.sun.imageio.plugins.jpeg.JPEG;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author BHAGAT
 */
public class FlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightPanel
     */
    private TravelAgency travelAgency;
    private Airliners airliners;
    private Airplane airplane;
    private JPanel cardSequenceJPanel;
    public FlightPanel(TravelAgency travelAgency,Airplane airplane, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.airliners=airplane.getFleet().getAirliners();
        this.airplane=airplane;
        this.cardSequenceJPanel=cardSequenceJPanel;
        loadAirplaneData();
    }
    
    private void loadAirplaneData()
    {
        airlinerTextField.setText(airliners.getAirlines());
        airplaneIdTextField.setText(String.valueOf(airplane.getAirplaneId()));
        manufacturingYearTextField.setText(String.valueOf(airplane.getManufacturingYear()));
        modelNumTextField.setText(airplane.getModelNumber());
        companyTextField.setText(airplane.getManufacturingCompany());
        totalSeatsTextField.setText(String.valueOf(airplane.getTotalSeats()));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        depaturePortTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        scheduleButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        companyTextField = new javax.swing.JTextField();
        manufacturingYearTextField = new javax.swing.JTextField();
        totalSeatsTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(211, 245, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage.png"))); // NOI18N
        jLabel1.setText("SCHEDULE FLIGHT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 320, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Flight Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        add(flightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Date (mm-dd-yyyy)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Time 24hrs (mm:ss)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, -1));
        add(depaturePortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 130, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Depature Port");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Destination Port");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));
        add(destinationPortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, -1));

        scheduleButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        scheduleButton.setText("Schedule");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });
        add(scheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 50));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("Price per Seat");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });
        add(pricePerSeatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 130, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setText("Airliner");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        airlinerTextField.setEnabled(false);
        add(airlinerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 140, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setText("Airplane Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        airplaneIdTextField.setEnabled(false);
        add(airplaneIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 140, -1));

        modelNumTextField.setEnabled(false);
        add(modelNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 140, -1));

        companyTextField.setEnabled(false);
        add(companyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 140, -1));

        manufacturingYearTextField.setEnabled(false);
        manufacturingYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingYearTextFieldActionPerformed(evt);
            }
        });
        add(manufacturingYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 140, -1));

        totalSeatsTextField.setEnabled(false);
        totalSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeatsTextFieldActionPerformed(evt);
            }
        });
        add(totalSeatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 140, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("Total Seats");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText("Manufacturing Year");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setText("Company");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setText("Model Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void manufacturingYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturingYearTextFieldActionPerformed

    private void totalSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeatsTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        // TODO add your handling code here:
        if((flightIdTextField.getText().isEmpty()) || (depaturePortTextField.getText().isEmpty()) ||
           (destinationPortTextField.getText().isEmpty()) || (dateTextField.getText().isEmpty()) ||
           (timeTextField.getText().isEmpty()) || (pricePerSeatTextField.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Please enter all the flight details", "Error", 0);
        }
        else
        {
            try
            {
                int id = Integer.parseInt(flightIdTextField.getText());
                double price = Double.parseDouble(pricePerSeatTextField.getText());
                if((id >=0) && (price >=0))
                {
                    try
                    {
                        byte flag = dateValidation(dateTextField.getText());
                        if(flag == 0)
                        {
                            SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy"); 
                            Date date = (Date)dateFormat.parse(dateTextField.getText());
                            Date currdate = (Date)dateFormat.parse(dateFormat.format(new Date()));
                            flag = timeValidation(timeTextField.getText());
                            if (flag == 0)
                            {
                                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
                                Date time = (Date)timeFormat.parse(timeTextField.getText());
                                Date currtime = (Date)timeFormat.parse(timeFormat.format(new Date()));
                                if (((date.equals(currdate)) && (time.after(currtime))) || (date.after(currdate)))
                                {
                                    Flight flight = airliners.getFlightSchedule().addFlight();
                                    flight.setAirplane(airplane);
                                    airplane.getAirplaneListOfFlight().add(flight);
                                    flight.setDepatureDate(dateTextField.getText());
                                    flight.setDepaturePort(depaturePortTextField.getText());
                                    flight.setDepatureTime(timeTextField.getText());
                                    flight.setDestinationPort(destinationPortTextField.getText());
                                    flight.setFlightId(id);
                                    flight.setPriceOfSeat(price);
                                    JOptionPane.showMessageDialog(null, "Filght Scheduled Successfully");
                                }
                                else 
                                    JOptionPane.showMessageDialog(null, "Please Enter Todays or future depature Date and time", "Error", 0);
                            }
                            else
                                JOptionPane.showMessageDialog(null, "Improper time format please enter time in HH:mm(24 hrs) format ", "Error", 0);
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Improper date format please enter date in MM-dd-yyyy format ", "Error", 0);
                    }
                    catch(Exception e)
                    {
                            JOptionPane.showMessageDialog(null, "Please enter date in MM-dd-yyyy & Time in HH:mm(24 hrs) format ", "Error", 0);
                            e.printStackTrace();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Flight Id and Price / Seat can't be negative", "Error", 0);
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Flight Id and Price per seat are numeric fields", "Error", 0);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_scheduleButtonActionPerformed

    private byte dateValidation(String depatDateTextField)
    {
        if (depatDateTextField.matches("^[0-1][0-9][-][0-3][0-9][-][0-9][0-9][0-9][0-9]"))
        {
               if (((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)<'3')) ||
                   ((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)<='9')))
               {
                    if (((depatDateTextField.charAt(3)=='0') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='1') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='2') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)<'2')))
                    {
                         if(((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)=='2') &&
                             (depatDateTextField.charAt(3)=='3')) || 
                            ((depatDateTextField.charAt(0)=='0') && ((depatDateTextField.charAt(1)=='4') || (depatDateTextField.charAt(1)=='6') ||
                                                                              (depatDateTextField.charAt(1)=='9')) &&
                                                                             (depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)=='1') ) ||
                            ((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)=='1') && (depatDateTextField.charAt(3)=='3') && 
                                 (depatDateTextField.charAt(4)=='1') ))
                         {
                               return 1;
                         }
                         else
                         {
                               return 0;
                         }
                    }
                     
                }
                            
        }
        return 1;                      
    }
    
    private byte timeValidation(String depatTimeTextField)
    {
        if (depatTimeTextField.matches("^[0-2][0-9][:][0-5][0-9]"))
        {
            if (((depatTimeTextField.charAt(0)=='2') && (depatTimeTextField.charAt(1) < '4')) ||
                 ((depatTimeTextField.charAt(0)=='1') && (depatTimeTextField.charAt(1) <='9'))||
                 ((depatTimeTextField.charAt(0)=='0') && (depatTimeTextField.charAt(1) <='9')))
            {
                return 0;
            }
        }
        return 1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField depaturePortTextField;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField manufacturingYearTextField;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField totalSeatsTextField;
    // End of variables declaration//GEN-END:variables
}
