/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author BHAGAT
 */
public class ListOfAirlinersPanel extends javax.swing.JPanel {

    /** Creates new form ListOfAirlinersPanel */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public ListOfAirlinersPanel(TravelAgency travelAgency,JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }

    public void reload()
    {
        DefaultTableModel dtm = (DefaultTableModel)airlinersTable.getModel();
        dtm.setRowCount(0);
        for (Map.Entry<String,Airliners> it : travelAgency.getListOfAirliner().entrySet())
        {
            Object row[] = new Object[1];
            row[0] = it.getValue();
            dtm.addRow(row);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinersTable = new javax.swing.JTable();
        viewDetailsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jButton3.setText("<< Back");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("                Airplane");

        setBackground(new java.awt.Color(209, 243, 243));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 81, 147, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        jLabel2.setText("LIST OF AIRLINERS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 315, -1));

        airlinersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinersTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 88, 385, 136));

        viewDetailsButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        viewDetailsButton.setText("View Details");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });
        add(viewDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 142, 147, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 42, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinersTable.getSelectedRow();
        if (selectedRow < 0 )
            JOptionPane.showMessageDialog(null, "Please select a row");
        else
        {
            Airliners airliners = (Airliners)airlinersTable.getValueAt(selectedRow,0);
            ViewAirlinerPanel viewAirlinerPanel = new ViewAirlinerPanel(airliners,cardSequenceJPanel);
            cardSequenceJPanel.add("ViewAirlinerPanel",viewAirlinerPanel);
            CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
            cardLayout.next(cardSequenceJPanel);    
        }
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinersTable;
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables

}
