/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirliners;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author BHAGAT
 */
public class ManageAirliners extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public ManageAirliners(TravelAgency travelAgency,JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createtAirlinerButton = new javax.swing.JButton();
        listOfAirlinersButton = new javax.swing.JButton();
        createFlightButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(212, 248, 248));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        jLabel1.setText("MANAGE AIRLINERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 340, -1));

        createtAirlinerButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        createtAirlinerButton.setText("Create Airliner");
        createtAirlinerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createtAirlinerButtonActionPerformed(evt);
            }
        });
        add(createtAirlinerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 86, 244, 50));

        listOfAirlinersButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        listOfAirlinersButton.setText("List of Airliner");
        listOfAirlinersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfAirlinersButtonActionPerformed(evt);
            }
        });
        add(listOfAirlinersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 144, 244, 50));

        createFlightButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        createFlightButton.setText("Create Flight");
        createFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightButtonActionPerformed(evt);
            }
        });
        add(createFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 207, 244, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 278, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void listOfAirlinersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfAirlinersButtonActionPerformed
        // TODO add your handling code here:
        ListOfAirlinersPanel listOfAirlinersPanel = new ListOfAirlinersPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("ListOfAirliners",listOfAirlinersPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_listOfAirlinersButtonActionPerformed

    private void createtAirlinerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createtAirlinerButtonActionPerformed
        // TODO add your handling code here:
        CreateAirlinerPanel createAirlinerPanel = new CreateAirlinerPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("CreateAirliner",createAirlinerPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_createtAirlinerButtonActionPerformed

    private void createFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightButtonActionPerformed
        // TODO add your handling code here:
        AirlinerForFlightPanel airlinerForFlightPanel = new AirlinerForFlightPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("AirlerForFlight",airlinerForFlightPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_createFlightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createFlightButton;
    private javax.swing.JButton createtAirlinerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listOfAirlinersButton;
    // End of variables declaration//GEN-END:variables
}
