/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageFlightSchedules;
import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.JobAttributes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHAGAT
 */
public class ViewUpdateFlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateFlightPanel
     */
    private Flight flight;
    private JPanel cardSequenceJPanel;
    public ViewUpdateFlightPanel(Flight flight, JPanel cardSequenceJPanel) {
        initComponents();
        this.flight=flight;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }
    
    public void reload()
    {
        flightIdTextField.setText(String.valueOf(flight.getFlightId()));
        dateTextField.setText(flight.getDepatureDate());
        timeTextField.setText(flight.getDepatureTime());
        depaturePortTextField.setText(flight.getDepaturePort());
        destinationPortTextField.setText(flight.getDestinationPort());
        pricePerSeatTextField.setText(String.valueOf(flight.getPriceOfSeat()));
        airlinerTextField.setText(flight.getAirplane().getFleet().getAirliners().getAirlines());
        airplaneIdTextField.setText(String.valueOf(flight.getAirplane().getAirplaneId()));
        manufacturingYearTextField.setText(String.valueOf(flight.getAirplane().getManufacturingYear()));
        modelNumTextField.setText(flight.getAirplane().getModelNumber());
        companyTextField1.setText(flight.getAirplane().getManufacturingCompany());
        totalSeatsTextField.setText(String.valueOf(flight.getAirplane().getTotalSeats()));
        DefaultTableModel dtm = (DefaultTableModel) seatsTable.getModel();
        dtm.setRowCount(0);
        for(Seat s: flight.getListOfSeats() )
        {
            Object row[]=new Object[3];
            row[0]=s;
            if(s.isBooked())
            {
                row[1]="Booked";
                row[2]=s.getPerson().getPersonId();
            }
            else
            {
                row[1]="Available";
                row[2]=null;
            }  
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        companyTextField1 = new javax.swing.JTextField();
        manufacturingYearTextField = new javax.swing.JTextField();
        totalSeatsTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        depaturePortTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        seatsTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelFlightButton = new javax.swing.JButton();
        undoCancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(220, 249, 249));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 50));

        jLabel1.setBackground(new java.awt.Color(210, 246, 246));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        jLabel1.setText("VIEW AND UPDATE FLIGHT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 450, -1));

        pricePerSeatTextField.setEnabled(false);
        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });
        add(pricePerSeatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 311, 110, -1));

        jLabel11.setText("Airplane Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 133, -1, -1));

        airplaneIdTextField.setEnabled(false);
        add(airplaneIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 127, 110, -1));

        modelNumTextField.setEnabled(false);
        add(modelNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 173, 110, -1));

        companyTextField1.setEnabled(false);
        add(companyTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 219, 110, -1));

        manufacturingYearTextField.setEnabled(false);
        manufacturingYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingYearTextFieldActionPerformed(evt);
            }
        });
        add(manufacturingYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 265, 110, -1));

        totalSeatsTextField.setEnabled(false);
        totalSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeatsTextFieldActionPerformed(evt);
            }
        });
        add(totalSeatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 311, 110, -1));

        jLabel2.setText("Flight Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 85, -1, -1));

        jLabel9.setText("Total Seats");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 317, -1, -1));

        flightIdTextField.setEnabled(false);
        add(flightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 79, 110, -1));

        jLabel8.setText("Manufacturing Year");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 271, -1, -1));

        jLabel3.setText("Date (mm-dd-yyyy)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 133, -1, -1));

        dateTextField.setEnabled(false);
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 127, 110, -1));

        jLabel4.setText("Time 24hrs (mm:ss)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 179, -1, -1));

        timeTextField.setEnabled(false);
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 173, 110, -1));

        jLabel12.setText("Company");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 225, -1, -1));

        jLabel13.setText("Model Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 179, -1, -1));

        depaturePortTextField.setEnabled(false);
        add(depaturePortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 219, 110, -1));

        jLabel5.setText("Depature Port");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 225, -1, -1));

        jLabel6.setText("Destination Port");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 271, -1, -1));

        destinationPortTextField.setEnabled(false);
        add(destinationPortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 265, 110, -1));

        jLabel10.setText("Airliner");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 85, -1, -1));

        airlinerTextField.setEnabled(false);
        airlinerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerTextFieldActionPerformed(evt);
            }
        });
        add(airlinerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 110, -1));

        jLabel7.setText("Price per Seat");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 317, -1, -1));

        seatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Num", "Status", "Customer Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(seatsTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 474, 107));

        updateButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 50));

        changeButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        changeButton.setText("Change Airplane");
        changeButton.setEnabled(false);
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        add(changeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 50));

        jLabel14.setText("Seats Allotment");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        saveButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, 50));

        cancelFlightButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        cancelFlightButton.setText("Cancel Flight");
        cancelFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFlightButtonActionPerformed(evt);
            }
        });
        add(cancelFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 50));

        undoCancelButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        undoCancelButton.setText("Undo Cancel Flight");
        undoCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoCancelButtonActionPerformed(evt);
            }
        });
        add(undoCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 340, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void manufacturingYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturingYearTextFieldActionPerformed

    private void totalSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeatsTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Component component = cardSequenceJPanel.getComponent((cardSequenceJPanel.getComponentCount()-2));
        ListOfFlightsPanel listOfFlightsPanel = (ListOfFlightsPanel) component;
        listOfFlightsPanel.reload();
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        dateTextField.setEnabled(true);
        timeTextField.setEnabled(true);
        depaturePortTextField.setEnabled(true);
        destinationPortTextField.setEnabled(true);
        pricePerSeatTextField.setEnabled(true);
        saveButton.setEnabled(true);
        changeButton.setEnabled(true);
        updateButton.setEnabled(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        AirplaneForFlightPanel airplaneForFlightPanel = new AirplaneForFlightPanel(flight,cardSequenceJPanel);
        cardSequenceJPanel.add("AirplaneForFlight",airplaneForFlightPanel);
        CardLayout cardLayout=(CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_changeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if((flightIdTextField.getText().isEmpty()) || (depaturePortTextField.getText().isEmpty()) ||
           (destinationPortTextField.getText().isEmpty()) || (dateTextField.getText().isEmpty()) ||
           (timeTextField.getText().isEmpty()) || (pricePerSeatTextField.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Please enter all the flight details", "Error", 0);
        }
        else
        {
            try
            {
                int id = Integer.parseInt(flightIdTextField.getText());
                double price = Double.parseDouble(pricePerSeatTextField.getText());
                if((id >=0) && (price >=0))
                {
                    try
                    {
                        byte flag = dateValidation(dateTextField.getText());
                        if(flag == 0)
                        {
                            SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy"); 
                            Date date = (Date)dateFormat.parse(dateTextField.getText());
                            Date currdate = (Date)dateFormat.parse(dateFormat.format(new Date()));
                            flag = timeValidation(timeTextField.getText());
                            if (flag == 0)
                            {
                                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
                                Date time = (Date)timeFormat.parse(timeTextField.getText());
                                Date currtime = (Date)timeFormat.parse(timeFormat.format(new Date()));
                                if (((date.equals(currdate)) && (time.after(currtime))) || (date.after(currdate)))
                                {
                                    flight.setDepatureDate(dateTextField.getText());
                                    flight.setDepaturePort(depaturePortTextField.getText());
                                    flight.setDepatureTime(timeTextField.getText());
                                    flight.setDestinationPort(destinationPortTextField.getText());
                                    flight.setFlightId(id);
                                    flight.setPriceOfSeat(price);
                                    JOptionPane.showMessageDialog(null, "Filght updated Successfully");
                                    dateTextField.setEnabled(false);
                                    timeTextField.setEnabled(false);
                                    depaturePortTextField.setEnabled(false);
                                    destinationPortTextField.setEnabled(false);
                                    pricePerSeatTextField.setEnabled(false);
                                    saveButton.setEnabled(false);
                                    changeButton.setEnabled(false);
                                    updateButton.setEnabled(true);
                                }
                                else 
                                    JOptionPane.showMessageDialog(null, "Please Enter Todays or future depature Date and time", "Error", 0);
                            }
                            else
                                JOptionPane.showMessageDialog(null, "Improper time format please enter time in HH:mm(24 hrs) format ", "Error", 0);
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Improper date format please enter date in MM-dd-yyyy format ", "Error", 0);
                    }
                    catch(Exception e)
                    {
                            JOptionPane.showMessageDialog(null, "Please enter date in MM-dd-yyyy & Time in HH:mm(24 hrs) format ", "Error", 0);
                            e.printStackTrace();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Price / Seat can't be negative", "Error", 0);
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Flight Id and Price per seat are numeric fields", "Error", 0);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFlightButtonActionPerformed
        // TODO add your handling code here:
        if(flight.isCancelFlag())
        {
            JOptionPane.showMessageDialog(null, "Flight is already cancelled! Press Undo Cancel to make flight available");
        }
        else
        {
            flight.setCancelFlag(true);
            JOptionPane.showMessageDialog(null,"Flight Cancelled Successfully");
        }
        
    }//GEN-LAST:event_cancelFlightButtonActionPerformed

    private void undoCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoCancelButtonActionPerformed
        // TODO add your handling code here:
        if(flight.isCancelFlag())
        {
            flight.setCancelFlag(false);
            JOptionPane.showMessageDialog(null,"Flight is Available now");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Flight is already Available press CancelFlight to cancel flight");
        }
    }//GEN-LAST:event_undoCancelButtonActionPerformed

    private void airlinerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerTextFieldActionPerformed


    private byte dateValidation(String depatDateTextField)
    {
        if (depatDateTextField.matches("^[0-1][0-9][-][0-3][0-9][-][0-9][0-9][0-9][0-9]"))
        {
               if (((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)<'3')) ||
                   ((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)<='9')))
               {
                    if (((depatDateTextField.charAt(3)=='0') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='1') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='2') && (depatDateTextField.charAt(4)<='9')) ||
                        ((depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)<'2')))
                    {
                         if(((depatDateTextField.charAt(0)=='0') && (depatDateTextField.charAt(1)=='2') &&
                             (depatDateTextField.charAt(3)=='3')) || 
                            ((depatDateTextField.charAt(0)=='0') && ((depatDateTextField.charAt(1)=='4') || (depatDateTextField.charAt(1)=='6') ||
                                                                              (depatDateTextField.charAt(1)=='9')) &&
                                                                             (depatDateTextField.charAt(3)=='3') && (depatDateTextField.charAt(4)=='1') ) ||
                            ((depatDateTextField.charAt(0)=='1') && (depatDateTextField.charAt(1)=='1') && (depatDateTextField.charAt(3)=='3') && 
                                 (depatDateTextField.charAt(4)=='1') ))
                         {
                               return 1;
                         }
                         else
                         {
                               return 0;
                         }
                    }
                     
                }
                            
        }
        return 1;                      
    }
    
    private byte timeValidation(String depatTimeTextField)
    {
        if (depatTimeTextField.matches("^[0-2][0-9][:][0-5][0-9]"))
        {
            if (((depatTimeTextField.charAt(0)=='2') && (depatTimeTextField.charAt(1) < '4')) ||
                 ((depatTimeTextField.charAt(0)=='1') && (depatTimeTextField.charAt(1) <='9'))||
                 ((depatTimeTextField.charAt(0)=='0') && (depatTimeTextField.charAt(1) <='9')))
            {
                return 0;
            }
        }
        return 1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelFlightButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField companyTextField1;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField depaturePortTextField;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField manufacturingYearTextField;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable seatsTable;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField totalSeatsTextField;
    private javax.swing.JButton undoCancelButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
