/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageCustomers;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author BHAGAT
 */
public class BookFlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightPanel
     */
    private TravelAgency travelAgency;
    private Flight flight;
    private JPanel cardSequenceJPanel;
    public BookFlightPanel(TravelAgency travelAgency,Flight flight, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.flight=flight;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }
    private void reload()
    {
        flightIdTextField.setText(String.valueOf(flight.getFlightId()));
        dateTextField.setText(flight.getDepatureDate());
        timeTextField.setText(flight.getDepatureTime());
        depaturePortTextField.setText(flight.getDepaturePort());
        destinationPortTextField.setText(flight.getDestinationPort());
        pricePerSeatTextField.setText(String.valueOf(flight.getPriceOfSeat()));
        airlinerTextField.setText(flight.getAirplane().getFleet().getAirliners().getAirlines());
        airplaneIdTextField.setText(String.valueOf(flight.getAirplane().getAirplaneId()));
        manufacturingYearTextField.setText(String.valueOf(flight.getAirplane().getManufacturingYear()));
        modelNumTextField.setText(flight.getAirplane().getModelNumber());
        companyTextField1.setText(flight.getAirplane().getManufacturingCompany());
        totalSeatsTextField.setText(String.valueOf(flight.getAirplane().getTotalSeats()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        depaturePortTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        companyTextField1 = new javax.swing.JTextField();
        manufacturingYearTextField = new javax.swing.JTextField();
        totalSeatsTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        bookButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pricePerSeatTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(217, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 149, 110, 43));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage.png"))); // NOI18N
        jLabel1.setText("FLIGHT BOOKING");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 350, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Flight Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 87, -1, -1));

        flightIdTextField.setEnabled(false);
        add(flightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 81, 130, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("Date (mm-dd-yyyy)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 133, -1, -1));

        dateTextField.setEnabled(false);
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 127, 130, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Time 24hrs (mm:ss)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 179, -1, -1));

        timeTextField.setEnabled(false);
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 173, 130, -1));

        depaturePortTextField.setEnabled(false);
        add(depaturePortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 225, 130, -1));

        modelNumTextField.setEnabled(false);
        add(modelNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 140, -1));

        companyTextField1.setEnabled(false);
        add(companyTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 140, -1));

        manufacturingYearTextField.setEnabled(false);
        manufacturingYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingYearTextFieldActionPerformed(evt);
            }
        });
        add(manufacturingYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 140, -1));

        totalSeatsTextField.setEnabled(false);
        totalSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSeatsTextFieldActionPerformed(evt);
            }
        });
        add(totalSeatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 140, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setText("Total Seats");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setText("Manufacturing Year");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("Company");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Model Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("Depature Port");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 231, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("Destination Port");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 285, -1, -1));

        destinationPortTextField.setEnabled(false);
        add(destinationPortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 279, 130, -1));

        bookButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 221, 110, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel7.setText("Price per Seat");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 331, -1, -1));

        pricePerSeatTextField.setEnabled(false);
        pricePerSeatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricePerSeatTextFieldActionPerformed(evt);
            }
        });
        add(pricePerSeatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 325, 130, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setText("Airliner");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        airlinerTextField.setEnabled(false);
        add(airlinerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 140, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setText("Airplane Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        airplaneIdTextField.setEnabled(false);
        add(airplaneIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 140, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manufacturingYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturingYearTextFieldActionPerformed

    private void totalSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSeatsTextFieldActionPerformed

    private void pricePerSeatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricePerSeatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePerSeatTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        ConfirmSeatPanel confirmSeatPanel = new ConfirmSeatPanel(travelAgency,flight,cardSequenceJPanel);
        cardSequenceJPanel.add("ConfirmSeat",confirmSeatPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_bookButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookButton;
    private javax.swing.JTextField companyTextField1;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField depaturePortTextField;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField manufacturingYearTextField;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField pricePerSeatTextField;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField totalSeatsTextField;
    // End of variables declaration//GEN-END:variables
}
