/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageCustomers;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHAGAT
 */
public class ConfirmSeatPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmSeatPanel
     */
    private TravelAgency travelAgency;
    private Flight flight;
    private JPanel cardSequenceJPanel;
    public ConfirmSeatPanel(TravelAgency travelAgency,Flight flight, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.flight=flight;
        this.cardSequenceJPanel=cardSequenceJPanel;
        reload();
    }
    private void reload()
    {
        airlinerTextField.setText(flight.getAirplane().getFleet().getAirliners().getAirlines());
        flightIdTextField.setText(String.valueOf(flight.getFlightId()));
        DefaultTableModel dtm = (DefaultTableModel) seatsTable.getModel();
        dtm.setRowCount(0);
        for(Seat s: flight.getListOfSeats() )
        {
            if(!(s.isBooked()))
            {
                Object row[]=new Object[2];
                row[0]=s;
                row[1]=flight.getPriceOfSeat();
                
                dtm.addRow(row);
            }
        }
        dtm = (DefaultTableModel) custTable.getModel();
        dtm.setRowCount(0);
        for(Person p:travelAgency.getCustomerDirectory().getListOfPerson())
        {
            Object row[] = new Object[2];
            row[0]=p;
            row[1]=p.getName();
          
            dtm.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        seatsTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        flightIdTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        viewDetailsButton = new javax.swing.JButton();
        bookButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        custIdTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(213, 245, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageCustomers/Webp.net-resizeimage-2.png"))); // NOI18N
        jLabel1.setText("SEAT CONFIRMATION ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 400, -1));

        seatsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(seatsTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 93, 390, 107));

        searchButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 228, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 222, 110, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("Airliner");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 59, -1, -1));

        airlinerTextField.setEnabled(false);
        add(airlinerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 53, 120, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Flight Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        flightIdTextField.setEnabled(false);
        add(flightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 53, 120, -1));

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(custTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 270, 390, 86));

        viewDetailsButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        viewDetailsButton.setText("View Details");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });
        add(viewDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 50));

        bookButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("Customer Details:-");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 381, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 427, -1, -1));
        add(custNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 421, 110, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("Id");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 427, -1, -1));

        custIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdTextFieldActionPerformed(evt);
            }
        });
        add(custIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 421, 100, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel7.setText("Email Id");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 427, -1, -1));
        add(emailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 421, 110, -1));

        addCustomerButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });
        add(addCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 320, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", "Economy- Window"},
                {"B", "Economy- Middle"},
                {"C", "Economy- Aisle"},
                {"D", "Business- Window"},
                {"E", "Business- Middle"},
                {"F", "Business- Aisle"}
            },
            new String [] {
                "Seats", "Seat Position"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 280, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void custIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(nameTextField.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Please enter the name before searching", "Error", 0);
        else
        {
            DefaultTableModel dtm = (DefaultTableModel) custTable.getModel();
            dtm.setRowCount(0);
            for(Person p:travelAgency.getCustomerDirectory().getListOfPerson())
            {
                if((p.getName()).toLowerCase().matches((nameTextField.getText()).toLowerCase()))
                {
                    Object row[]=new Object[2];
                    row[0]=p;
                    row[1]=p.getName();
                    dtm.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = custTable.getSelectedRow();
        
        
        if (selectedRow < 0 )
            JOptionPane.showMessageDialog(null, "Please select a row from Customer Table");
        else
        {
            addCustomerButton.setEnabled(false);
            custIdTextField.setEnabled(false);
            custNameTextField.setEnabled(false);
            emailIdTextField.setEnabled(false);
            Person p = (Person) custTable.getValueAt(selectedRow, 0);
            
            custIdTextField.setText(String.valueOf(p.getPersonId()));
            custNameTextField.setText(p.getName());
            emailIdTextField.setText(p.getEmailId());
            addCustomerButton.setEnabled(false);
            
            
            ViewJPanel vPanel = new ViewJPanel(travelAgency, flight, cardSequenceJPanel,p);
            cardSequenceJPanel.add("ViewJPanel",vPanel);
            CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
            layout.next(cardSequenceJPanel);
        }
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        if((custIdTextField.getText().isEmpty()) || (custNameTextField.getText().isEmpty()) || (emailIdTextField.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer name,id and email-id", "Error", 0);
        }
        else
        {
            try
            {
                int id = Integer.parseInt(custIdTextField.getText());
                Person person= travelAgency.getCustomerDirectory().addPerson();
                person.setEmailId(emailIdTextField.getText());
                person.setName(custNameTextField.getText());
                person.setPersonId(id);
                reload();
                custIdTextField.setText("");
                custNameTextField.setText("");
                emailIdTextField.setText("");
                addCustomerButton.setEnabled(false);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Please enter numeric data in customer id", "Error", 0);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = custTable.getSelectedRow();
        int selectRow1= seatsTable.getSelectedRow();
        if ((selectedRow < 0 ) || (selectRow1 < 0))
            JOptionPane.showMessageDialog(null, "Please select a customer from Customer Table and a seat from Seats Table for Booking the seat");
        else
        { 
            Person p = (Person) custTable.getValueAt(selectedRow, 0);
            Seat s = (Seat) seatsTable.getValueAt(selectRow1, 0);
            s.setPerson(p);
            s.setBooked(true);
            p.addSeat(s);
            custIdTextField.setText("");
            custNameTextField.setText("");
            emailIdTextField.setText("");
            addCustomerButton.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Seat Booked Successfully");
            reload();
        }
    }//GEN-LAST:event_bookButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookButton;
    private javax.swing.JTextField custIdTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTable custTable;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JTextField flightIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable seatsTable;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
}
