/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageCustomers;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author BHAGAT
 */
public class ManageCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerPanel
     */
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;
    public ManageCustomerPanel(TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency=travelAgency;
        this.cardSequenceJPanel=cardSequenceJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bestFlightButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(221, 249, 249));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage-5.png"))); // NOI18N
        jLabel1.setText("MANAGE CUSTOMER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, -1));

        bestFlightButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        bestFlightButton.setText("Best Flight");
        bestFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestFlightButtonActionPerformed(evt);
            }
        });
        add(bestFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 136, 42));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 265, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bestFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestFlightButtonActionPerformed
        // TODO add your handling code here:
        BestFlightPanel bestFlightPanel = new BestFlightPanel(travelAgency,cardSequenceJPanel);
        cardSequenceJPanel.add("BestFlight",bestFlightPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);
    }//GEN-LAST:event_bestFlightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bestFlightButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
