/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageCustomers;
import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.JobAttributes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sayalibhagat
 */


public class ViewJPanel extends javax.swing.JPanel {
private TravelAgency travelAgency;
private Flight flight;
private JPanel cardSequenceJPanel;
private Person p;
private Seat s;
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(TravelAgency travelAgency,Flight flight, JPanel cardSequenceJPanel,Person p) {
        initComponents();
        this.travelAgency=travelAgency;
        this.flight=flight;
        this.cardSequenceJPanel=cardSequenceJPanel;
        
        this.p=p;
        this.s=s;
        CustomerNameTextField.setText(p.getName());
        EmailTextField.setText(p.getEmailId());
        CustomerIdTextField.setText(String.valueOf(p.getPersonId()));
        BookedAirlinerTextField.setText(flight.getAirplane().getFleet().getAirliners().getAirlines());
        FlightIdTextField.setText(String.valueOf(flight.getFlightId()));
        PriceTextField.setText(String.valueOf(flight.getPriceOfSeat()));
        FlightDateTextField.setText(String.valueOf(flight.getDepatureDate()));
        DestinationPortTextField.setText(String.valueOf(flight.getDestinationPort()));
        DeparturePortTextField.setText(String.valueOf(flight.getDepaturePort()));
        FlightTimeTextField.setText(String.valueOf(flight.getDepatureTime()));   
        
    
    }
    ViewJPanel(TravelAgency travelAgency, Flight flight, JPanel cardSequenceJPanel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        CustomerNameTextField = new javax.swing.JTextField();
        BookedAirlinerTextField = new javax.swing.JTextField();
        FlightIdTextField = new javax.swing.JTextField();
        FlightTimeTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        StatusTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CustomerIdTextField = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        DeparturePortTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DestinationPortTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FlightDateTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(203, 241, 241));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage.png"))); // NOI18N
        jLabel1.setText("VIEW CUSTOMER BOOKING DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 530, 33));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Customer Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("Email Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Booked Airliner:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("Flight Id:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("Flight Timing:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel7.setText("Price:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setText("Booking Status:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 160, 180, 30));
        add(CustomerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 120, 180, 30));
        add(BookedAirlinerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 180, 30));
        add(FlightIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 30));
        add(FlightTimeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 180, 30));
        add(PriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 488, 180, 30));

        StatusTextField.setText("Booked");
        StatusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTextFieldActionPerformed(evt);
            }
        });
        add(StatusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 528, 180, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setText("Customer ID:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));
        add(CustomerIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 80, 180, 30));

        Back.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 40));

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMER DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 400, 150));
        add(DeparturePortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 180, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setText("Departure Port:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));
        add(DestinationPortTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 180, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("Destination Port:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FLIGHT DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 400, 350));
        add(FlightDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 180, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel14.setText("Flight Date:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_BackActionPerformed

    private void StatusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField BookedAirlinerTextField;
    private javax.swing.JTextField CustomerIdTextField;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JTextField DeparturePortTextField;
    private javax.swing.JTextField DestinationPortTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FlightDateTextField;
    private javax.swing.JTextField FlightIdTextField;
    private javax.swing.JTextField FlightTimeTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JTextField StatusTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
